src/config.py
src/helpers.py

replaced file variablename

---

README.md

[//]: # (====================)
[//]: # (Issue Related       )
[//]: # (====================)
[//]: # (The title must have the next format: Issue <Issue ID> - <Issue Name>)
**Principal Issue ID**: #31 
**Principal Issue Name**: CANTIDAD DE RECOMMENDATIONS
**Others related Issues**: #, #
[//]: # (<Completely / Just a part: Description of what is missing>)
Completely

Issue 31 - CANTIDAD DE RECOMMENDATIONS

---

.github/PULL_REQUEST_TEMPLATE.md

Completely fixes: #66
This PR follows the new template. Enjoy!

PR: Issue 66: Pull Request Template Changes

---

docs/CONTRIBUTING.md

PR: #76 : Added a working contributing.md file
Completely fixed issue #76 by creating a contributing.md file.

PR: #76 : Added a working contributing.md file

---

src/console/__main__.py
src/console/arguments.py
src/helpers/assets.py
src/helpers/fso.py
src/helpers/strings.py
src/helpers/validators.py
src/info.py
src/module/__main__.py
src/module/config/images.py
src/module/config/user.py
src/module/files/base.py
src/module/files/complementary_files.py
src/module/files/head/base.py
src/module/files/head/general.py
src/module/files/head/images.py
src/module/files/images.py
src/services/images.py
src/services/logs.py
src/support.py
testing/wasa.set

Completely fixes: #90
Not used the mapping.

PR: Issue 90: Usage of mapping proxy type

---

.github/auto-merge.yml

probot auto merge

---

.restyled.yaml

Restyled.io bot

---

.restyled.yaml

--- : *signal the start of a document*

Restyled.io miss --- ?

---

.restyled.yaml
src/support.py

test restyled.io bot

---

.restyled.yaml

PR: Issue 99: update restyled config

---

src/module/config/user.py

Testing restyled bot
Issue: #99

test restyled bot

---

.restyled.yaml

Test new config restyled bot
Issue #99

Test new config restyled bot

---

.restyled.yaml
src/module/config/images.py

issue #99 
<anything else you'd like to add>
1. <step>
2. <step>
3. <step>

pr: RESTYLED bot ISSUE #99 now test

---

.github/config.yml

PR: Issue 3: Welcome BOT

---

docs/CONTRIBUTING.md

<Completely/Partly> fixes: #<issue_that_PR_solves>
<anything else you'd like to add>
1. <step>
2. <step>
3. <step>

Issue 58 -

---

docs/CONTRIBUTING.md

<Completely/Partly> fixes: #<issue_that_PR_solves>
<anything else you'd like to add>
1. <step>
2. <step>
3. <step>

implement blockquote

---

.gitignore
.theia/settings.json

<Completely/Partly> fixes: #<issue_that_PR_solves>
<anything else you'd like to add>
1. <step>
2. <step>
3. <step>

testing gitpod

---

src/module/config/user.py
src/module/files/complementary_files.py

PR: Issue 83: Remove related applications manifest

---

src/base/generator/files.py
src/info.py

Add conditional for IE

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

Improvements in README.md and in ISSUES and PR templates.
Resolves: https://github.com/lucasvazq/cushead/issues/228

Improve in docs

---

.github/workflows/lighthouse.yml
.github/workflows/python-observer.yml
.github/workflows/release.yml
README.md
cushead/console/arguments/files_creator.py
cushead/info.py
setup.py

- Fixed the release action.
- Some improvements in the readme
- Add new version number
- Improve pathlib instances creation for better performance ⚡️ and for prevent redundant code 💩
- Prevent actions to be executed two times in the same PR

Some fixes and improvements
